# -*- coding: utf-8 -*-
"""num_gen

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3YWbtI5AzBF3USfPPfxaRyYOmwZ7cV5
"""

import random

total_size = 100000
with open("data.txt", 'w') as f:
    l = [i for i in range(1, total_size+1)]
    random.shuffle(l)
    print(len(l))
    for i in l:
      f.write('%d\n' % i)
f.close()

import random

total_size = 1000000
with open("data1.txt", 'w') as f:
    l = [i for i in range(1, total_size+1)]
    random.shuffle(l)
    print(len(l))
    for i in l:
      f.write('%d\n' % i)
f.close()

import random

total_size = 1000
with open("data2.txt", 'w') as f:
    l = [i for i in range(1, total_size+1)]
    random.shuffle(l)
    print(len(l))
    for i in l:
      f.write('%d\n' % i)
f.close()

import random

total_size = 10000
with open("data3.txt", 'w') as f:
    l = [i for i in range(1, total_size+1)]
    random.shuffle(l)
    print(len(l))
    for i in l:
      f.write('%d\n' % i)
f.close()

import random

total_size = 100
with open("data4.txt", 'w') as f:
    l = [i for i in range(1, total_size+1)]
    random.shuffle(l)
    print(len(l))
    for i in l:
      f.write('%d\n' % i)
f.close()